# Generated by Django 3.2.3 on 2021-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=254)),
                ('page', models.CharField(max_length=3)),
                ('pgender', models.CharField(max_length=7)),
                ('pcontact', models.CharField(max_length=15)),
                ('ppsw', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
