# Generated by Django 3.2.3 on 2021-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ppres',
            field=models.FileField(default='file', upload_to='files/'),
            preserve_default=False,
        ),
    ]
