# Generated by Django 3.2.3 on 2021-05-18 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_ppres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ppres',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
