# Generated by Django 3.2.3 on 2021-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_demail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='demail',
            field=models.EmailField(max_length=254),
        ),
    ]
