# Generated by Django 3.2.3 on 2021-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_demail'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dspec',
            field=models.CharField(default='General', max_length=30),
            preserve_default=False,
        ),
    ]
